### ISSUE TITLE
Load other .bot files

### ISSUE THREAD

**Issue by WitoDeGreef** [BotML/botml-js#3]
Is it possible to load other .bot files containing a workflow for example. I would like to create one mail file for my bot which will use workflows defined across different files which should be loaded at the beginning of the file. 

For example : 

```
! BOTML 1
[load file containing main-workflow]

# Bot

> Hi
~ main-workflow

**Comment by arnaud** [comment]
That's an interesting idea indeed.

Currently, you can't like this ; but you can require multiple .bot files via the command line like this:

```
node lib/cli.js examples/hello.bot examples/expressions.bot
```

The equivalent exists in JS (see the [source](https://github.com/BotML/botml-js/blob/master/src/botml.js#L25):

```
bot.load(['./examples/hello.bot', './examples/expressions.bot'])
```

**Comment by arnaud** [comment]
I feel that solutions have been provided; closing this issue now; please let me know if anything missing?
